### ISSUE TITLE
Atari7800 controller not displaying

### ISSUE THREAD

**Issue by rollecode** [anthonycaccese/es-theme-tft#1]
Hi, just noticed atari7800 icon is not displaying. Can you fix it?

**Comment by anthonycaccese** [comment]
Yes I'll take a look after finishing the update on Art Book Pocket.  Thank you

**Comment by rollecode** [comment]
I went ahead and edited myself. Here are my svgs, if you need them:
[system.svg](https://rolle.wtf/atari7800/_inc/system.svg) (didn't manage to get "/" char 100% perfect, maybe you can fix it, [download PSD](https://rolle.wtf/atari7800/_inc/system.psd))
[controller.svg](https://rolle.wtf/atari7800/_inc/controller.svg)
