### ISSUE TITLE
Permission to use theme on other devices

### ISSUE THREAD

**Issue by JackD83** [anthonycaccese/es-theme-tft#3]
Hi @anthonycaccese,
I would like to use your theme(s) and images on devices running [RetroFW](https://github.com/retrofw/retrofw.github.io). 
These devices use a low power ingenic mips processor and are not capable of running emulationstation. I wrote a little menu that mimics the look of es written in python [pymenu](https://github.com/JackD83/PyMenu) and would like to use use themes, but could not find a license. 

best regards,
Jack

**Comment by anthonycaccese** [comment]
Hi @JackD83, Yes please feel free to port this theme to work on pymenu.  That sounds awesome =)

Main thing I would ask is if you would be ok putting this credit in your readme when its done...
- This theme was ported from [es-theme-tft](https://github.com/anthonycaccese/es-theme-tft) by Anthony Caccese
- Controller graphics are from the [Carbon theme](https://github.com/RetroPie/es-theme-carbon/) by Eric Hettervik

I would also be glad to help with porting if it would help at all.  Just let me know.

**Comment by JackD83** [comment]
Fantastic! It will take some time to adapt it and I have to add some new theme options. Of course I will add the readme as you asked like for the other themes! Thank you very much!
